### ISSUE TITLE
Question about the oracle camera config

### ISSUE THREAD

**Issue by DeeDive** [cliport/cliport#12]
Hi authors, thanks for the great work! Can I ask a question about the camera configs of the oracle?

```
class Oracle(object):
    """Top-down noiseless image used only by the oracle demonstrator."""

    # Near-orthographic projection.
    image_size = (480, 640)
    intrinsics = (63e4, 0, 320.0, 0, 63e4, 240.0, 0, 0, 1)
    position = (0.5, 0, 1000.0)
    rotation = p.getQuaternionFromEuler((0, np.pi, -np.pi / 2))

    # Camera config.
    CONFIG = [
        {
            "image_size": image_size,
            "intrinsics": intrinsics,
            "position": position,
            "rotation": rotation,
            # "zrange": (999.7, 1001.0),
            "zrange": (999.7, 1001.0),
            "noise": False,
        }
    ]
```
Could you explain the meaning of different parameters in the config? I find that your camera could have perfect captures of the workspace without, e.g. margins. How did you achieve that? And more specifically, what does `"zrange": (999.7, 1001.0),` do? From my understanding, it set the camera at a height of 1000cm, right? I am a little bit confused about that because the height of the whole workspace is only 0.3. 

Millions of thanks in advance!

**Comment by MohitShridhar** [comment]
@DeeDive, this config was copied over from the TransporterNets codebase. 

These parameters represent a standard projection matrix (https://www.cse.psu.edu/~rtc12/CSE486/lecture12.pdf). `zrange` is the near and far plane of the projection.

These settings are designed to emulate a perfect orthographic camera from the top-down view. The camera is positioned very high up at 1000 and the near/far plane barely capture the workspace between 999.7 and 1001. This helps in avoiding any [perspective distortions](https://www.snapwerx.biz/wp-content/uploads/2013/11/perspective_distortion.jpg) that are common in pinhole camera. 

However, doing this with real cameras is hard. This is what our real-world config looked like:
```
class KinectFranka():
    """Kinect Franka Camera"""

    # Near-orthographic projection.
    image_size = (424,512)
    intrinsics = (365.57489013671875, 0.0, 257.5205078125, 0.0, 365.57489013671875, 205.26710510253906, 0.0, 0.0, 1.0)
    position = (1.082, -0.041, 1.027)
    rotation = p.getQuaternionFromEuler((-2.611, 0.010, 1.553))

    # Camera config.
    CONFIG = [{
        'image_size': image_size,
        'intrinsics': intrinsics,
        'position': position,
        'rotation': rotation,
        'zrange': (0.01, 10.),
        'noise': False
    }]
```

**Comment by DeeDive** [comment]
Thank you very much for your answers! It is really helpful! For the KinectFranka camera, are you using a human operator as the oracle to generate some data for training?

**Comment by MohitShridhar** [comment]
@DeeDive, you mean for the data collection of expert demonstrations? Yes, a human operates the robot like this: https://youtu.be/UdzoagBgWTA?t=29

If you are referring to the camera parameters, those were computed with standard camera calibration tools. I used [ia_kinect2](https://github.com/code-iai/iai_kinect2) for the Kinect.
