### ISSUE TITLE
Customizing image size

### ISSUE THREAD

**Issue by huangjy-pku** [cliport/cliport#15]
Hello, respect to your great job and generous release! I wonder if I can modify the image size for training?

I already figure out how to change input image resolution in `preprocess` module in `cliport/utils/utils.py`. I am not sure if it works. And could you please offer some guidance on how to change the resolution of ground truth label? In addition, I am not sure whether modifying these two places is enough for training at customized image size?

**Comment by MohitShridhar** [comment]
@huangjy-pku, yes, you can modify the image size. Unfortunately, the image size is hard coded in a number spots:
- https://github.com/cliport/cliport/blob/e9cde74754606448d8a0495c1efea36c29b201f1/cliport/tasks/cameras.py#L54
- https://github.com/cliport/cliport/blob/202f96e36eb247759bbec0840d4af2cb75a4e1a1/cliport/dataset.py#L42
- https://github.com/cliport/cliport/blob/e9cde74754606448d8a0495c1efea36c29b201f1/cliport/agents/transporter.py#L36
So you will have to modify all these. 

The ground-truth labels are automatically extracted from the hand-eye calibration, so it should just work once all the image sizes are fixed.

**Comment by huangjy-pku** [comment]
Thanks for your quick reply! Though, I got two more questions.

1. What happens from `image_size` in `cameras.py` to returned image in `dataset.py`, making their even inconsistent aspect ratio?

**Comment by huangjy-pku** [comment]
Finally I make the following solution: resize right before forwarding the observation to `stream_model`, and resize the dense output reversely back to the original resolution. So in this way the only modified part is the two ends of `stream_model`.

I found this work yet, and if there is any detail that I have not taken into consideration, please point it out and let me know. If not, I will close this issue :)
