### ISSUE TITLE
Training iterations with different numbers of demonstrations

### ISSUE THREAD

**Issue by geyuying** [cliport/cliport#17]
Thanks for your excellent work and perfect github repo.

I have a problem about the number of training iterations. Does 200K iterations are used for training a single task model on different numbers of demonstrations (1, 10, 100, or 1000)? For example, training on 1 demonstration also takes 200K iterations. Since max_epoch =  cfg['train']['n_steps'] // cfg['train']['n_demos'], does it mean training on fewer demonstrations takes more epochs？

Looking forward to your reply.

Best regards,
Yuying

**Comment by MohitShridhar** [comment]
@geyuying, that's right. All demonstration splits (1, 10, 100, 1000) were trained up to 200K iterations. 

With 1 demo, only a small set of image-action pairs will keep getting sampled over and over again, of course with data augmentation. 

You can also stop early if the evaluation performance has plateaued, but I did this 200K thing for the core experiments for a fair comparison.
