### ISSUE TITLE
About Visualization

### ISSUE THREAD

**Issue by ZhouYFeng** [cliport/cliport#24]
Hi Mohit,

I am trying the Cliport. But I run it on the remote GPU server by SSH. Because of the lack of GUI, the **disp** must be set as **False**.

I want to know how to visualize the process of simulation like the picture below.
(https://user-images.githubusercontent.com/111882855/223475809-8bb07371-791b-4380-9115-a212665b2bec.png)

Thanks.

**Comment by MohitShridhar** [comment]
@ZhouYFeng, if you don't have access to a display, you have to record rollouts using this: https://github.com/cliport/cliport#recording-videos
