### ISSUE TITLE
June 5th 2023 some package & version issue

### ISSUE THREAD

**Issue by Hollen0318** [cliport/cliport#33]
To run this on my Ubuntu 18.04, I need to do following (after following the instructions on the repo)

export PYTHONPATH=$(pwd)
export CLIPORT_ROOT=$(pwd)

pip install protobuf==3.20.0

Change the np.float into float in the quaternions.py (line 26 and 27)
pip install --upgrade transformers

**Comment by jeasinema** [comment]
Thanks for the fix! For me, I need one additional step to get rid of this error `ModuleNotFoundError: No module named 'torch.utils._pytree'`

```bash
pip install -U torch
```
