### ISSUE TITLE
a question about Generating demonstration data

### ISSUE THREAD

**Issue by luding110** [cliport/cliport#34]
Is the generated expert demonstration data fixed or random? For example, if I generate 'packing-boxes-pairs-seen-data-train' twice with n=1000, will the data be exactly the same both times?

**Comment by MohitShridhar** [comment]
sorry for the late reply,

The expert demonstrations should be fixed with the random seed, i.e. given the same random seed, you should be able to spawn the same environment everytime.

Hope this helps!
