### ISSUE TITLE
Can two robotic arms be generated to operate？

### ISSUE THREAD

**Issue by peppaaaaaaa** [cliport/cliport#37]
I ran the program and found that the generated videos were all of a robotic arm in motion. But I researched the code and couldn't find a definition for the number of robotic arms. Can this project generate two robotic arms for collaborative motion? Looking forward to your reply!

**Comment by MohitShridhar** [comment]
@peppaaaaaaa, in theory, a bimanual setup should be doable. You need to edit [environment.py](https://github.com/cliport/cliport/blob/master/cliport/environments/environment.py) to suit your needs. All expert demos should also be adapted to bimanual setups.

**Comment by peppaaaaaaa** [comment]
Thanks for your reply!  I have tried and successfully generated it.
