### ISSUE TITLE
Training with Fewer Demos and n_steps Adjustment

### ISSUE THREAD

**Issue by Noone65536** [cliport/cliport#38]
Hello,

Thanks for your great work. 

I have a question regarding your experiments. In the experiments where you trained the model with fewer demonstrations (like n_demo = 1, 10 ), did you also adjust the n_steps parameter accordingly?  In the paper you mentioned "we evaluate a trained agent across fixed checkpoints between 1K-200K iterations for single-task settings."  Does this mean for the same number of demos, you trained with different n_steps and then selected the checkpoint with the best performance? 

Thanks for clarifying,

Best regards

**Comment by MohitShridhar** [comment]
@Noone65536, sorry for the late reply. Yes, for all n_demos (1, 10, 100, 1000), the training iterations were fixed. This means for n=1, just a few images are sampled again and again (with data augmentation) for 200k iterations.
