### ISSUE TITLE
Affordance heatmap visualizer

### ISSUE THREAD

**Issue by sachit-menon** [cliport/cliport#4]
Hi, thanks for this great work and code release! I was wondering what the status is of the affordance heatmap visualizer (or the dataset visualizer too) - I see it's in the TODOs in the README. It'd make it much easier to build off of this work with that in hand to explore! Thanks and looking forward to hearing from you.

**Comment by MohitShridhar** [comment]
@sachit-menon, I need some time to clean up my spaghetti code.

But here is a quick snippet (probably broken) that you can [apply here](https://github.com/cliport/cliport/blob/master/cliport/agents/transporter_lang_goal.py#L106):
https://gist.github.com/MohitShridhar/7f5182ffedce4799a4a1cca9c603634f

**Comment by sachit-menon** [comment]
Hi Mohit, thanks for your quick reply. I'll try that gist out in the meantime.

**Comment by MohitShridhar** [comment]
@sachit-menon, done: https://github.com/cliport/cliport/blob/master/notebooks/affordances.ipynb
