### ISSUE TITLE
How to label custom annotation like in your vedio?

### ISSUE THREAD

**Issue by qingweihk** [cliport/cliport#6]
Hi, I notice in your youtube demo vedio:about 48s in the vedio:Folding Task Dataset:

you labeled picklabel by red and  place label by green.

May I ask whcih label tool you use to do such a label?

Thanks very much!

**Comment by MohitShridhar** [comment]
@qingweihk for the pick-and-place interface I wrote a simple OpenCV GUI application. See this [tutorial](https://stackoverflow.com/questions/50234485/drawing-rectangle-in-opencv-python) for drawing rectangles with a mouse. You will need to build a custom interface that suits your real-robot setup.

The visualizations at 48s are just Matplotlib.
